-- lista de tabelas
select * from dbpet.tipo_usuario;
select * from dbpet.endereco;
select * from dbpet.usuario;
select * from dbpet.forma_envio;
select * from dbpet.categoria;
select * from dbpet.produto;
select * from dbpet.status_pedido;
select * from dbpet.pedido;
select * from dbpet.item_pedido;
select * from dbpet.pagamento;
select * from dbpet.promocao;
select * from dbpet.promocoes_atuais;
select * from dbpet.forma_pagamento;
select * from dbpet.carrinho;
select * from dbpet.favoritos;
select * from dbpet.avaliacao;
select * from dbpet.estoque;
select * from dbpet.status_pagamento;
select * from dbpet.feedback;

-- drop table
drop table dbpet.feedback;
drop table dbpet.avaliacao;
drop table dbpet.pagamento;
drop table dbpet.status_pagamento;
drop table dbpet.carrinho;
drop table dbpet.favoritos;
drop table dbpet.promocoes_atuais;
drop table dbpet.item_pedido;
drop table dbpet.pedido;
drop table dbpet.endereco;
drop table dbpet.usuario;
drop table dbpet.estoque;
drop table dbpet.produto;
drop table dbpet.categoria;
drop table dbpet.tipo_usuario;
drop table dbpet.forma_envio;
drop table dbpet.status_pedido;
drop table dbpet.promocao;
drop table dbpet.forma_pagamento;
drop schema dbpet;