services:
  UserAPI:
    image: omg-user-api
    build: ./UserAPI
    container_name: user-api
    volumes:
      - ./UserAPI/system/OhMyDogAPI:/var/lib/omdapi
    ports:
      - "5010:8080"
    networks:
      - omd-network

  PromotionAPI:
    build: ./PromotionAPI
    image: omg-promotion-api
    container_name: promotion-api
    volumes:
      - ./system/OhMyDogAPI:/var/lib/omdapi
    ports:
      - "5069:8080"
    networks:
      - omd-network

  # ProductAPI:
  #   build: ./ProductAPI
  #   image: omg-product-api
  #   container_name: product-api
  #   volumes:
  #     - ./system/OhMyDogAPI:/var/lib/omdapi
  #   ports:
  #     - "5009:8080"
  #   networks:
  #     - omd-network

  # PaymentAPI:
  #   build: ./PaymentAPI
  #   image: omg-payment-api
  #   container_name: payment-api
  #   volumes:
  #     - ./system/OhMyDogAPI:/var/lib/omdapi
  #   ports:
  #     - "5009:8080"
  #   networks:
  #     - omd-network

  # OrderAPI:
  #   build: ./OrderAPI
  #   image: omg-order-api
  #   container_name: order-api
  #   volumes:
  #     - ./system/OhMyDogAPI:/var/lib/omdapi
  #   ports:
  #     - "5009:8080"
  #   networks:
  #     - omd-network

  # InventoryAPI:
  #   build: ./InventoryAPI
  #   image: omg-inventory-api
  #   container_name: inventory-api
  #   volumes:
  #     - ./system/OhMyDogAPI:/var/lib/omdapi
  #   ports:
  #     - "5009:8080"
  #   networks:
  #     - omd-network

  db:
    image: postgres:latest
    build: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - omd-network
    container_name: db-ecommerce-postgres
    volumes:
      - /home/amanda/PostgreSQL:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2023!

  pgAdmin:
    image: dpage/pgadmin4
    build: dpage/pgadmin4
    ports:
      - "15432:80"
    networks:
      - omd-network
    container_name: pgadmin
    volumes:
      - /home/amanda/pgadmin:/var/lib/pgadmin/data
    environment:
      PGADMIN_DEFAULT_EMAIL: amanda.pagani@aluno.faculdadeimpacta.com.br
      PGADMIN_DEFAULT_PASSWORD: PgAdmin2023!

networks:
  omd-network:
    driver: bridge
