services:
  UserAPI:
    image: omd-user-api
    build: ./UserAPI
    container_name: user-api
    volumes:
      - ./UserAPI/system/OhMyDogAPI:/var/lib/omdapi
    ports:
      - "5010:8080"
    networks:
      - omd-network

  PromotionAPI:
    build: ./PromotionAPI
    image: omd-promotion-api
    container_name: promotion-api
    volumes:
      - ./PromotionAPI/system/OhMyDogAPI:/var/lib/omdapi
    ports:
      - "5069:8080"
    networks:
      - omd-network

  ProductAPI:
    build: ./ProductAPI
    image: omd-product-api
    container_name: product-api
    volumes:
      - ./ProductAPI/system/OhMyDogAPI:/var/lib/omdapi
    ports:
      - "5051:8080"
    networks:
      - omd-network

  PaymentAPI:
    build: ./PaymentAPI
    image: omd-payment-api
    container_name: payment-api
    volumes:
      - ./PaymentAPI/system/OhMyDogAPI:/var/lib/omdapi
    ports:
      - "5228:8080"
    networks:
      - omd-network

  OrderAPI:
    build: ./OrderAPI
    image: omd-order-api
    container_name: order-api
    volumes:
      - ./OrderAPI/system/OhMyDogAPI:/var/lib/omdapi
    ports:
      - "5053:8080"
    networks:
      - omd-network

  InventoryAPI:
    build: ./InventoryAPI
    image: omd-inventory-api
    container_name: inventory-api
    volumes:
      - ./InventoryAPI/system/OhMyDogAPI:/var/lib/omdapi
    ports:
      - "5082:8080"
    networks:
      - omd-network

  AdministratorAPI:
    build: ./AdministratorAPI
    image: omd-administrator-api
    container_name: administrator-api
    volumes:
      - ./AdministratorAPI/system/OhMyDogAPI:/var/lib/omdapi
    ports:
      - "5143:8080"
    networks:
      - omd-network

  EmailAPI:
    build: ./EmailAPI
    image: omd-email-api
    env_file:
      - ./EmailAPI/.env
    container_name: email-api
    volumes:
      - ./EmailAPI/system/OhMyDogAPI:/var/lib/omdapi
    ports:
      - "5079:8080"
    networks:
      - omd-network

  db:
    image: postgres:16.0
    build: postgres:16.0
    ports:
      - "5432:5432"
    networks:
      - omd-network
    container_name: db-ecommerce-postgres
    volumes:
      - /home/amanda/PostgreSQL:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-entrypoint-initdb.d/script_dbecommerce.sql:/docker-entrypoint-initdb.d/script_dbecommerce.sql
      - ./docker-entrypoint-initdb.d/inserts.sql:/docker-entrypoint-initdb.d/inserts.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2023!

  pgAdmin:
    image: dpage/pgadmin4:latest
    build: dpage/pgadmin4:latest
    ports:
      - "15432:80"
    networks:
      - omd-network
    container_name: pgadmin
    volumes:
      - /home/amanda/pgadmin:/var/lib/pgadmin/data
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADM__EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${EMAIL__PASSWORD}

networks:
  omd-network:
    driver: bridge
