@EmailAPI_HostAddress = http://localhost:5079

POST {{EmailAPI_HostAddress}}/api/Email/SendEmail
Accept: application/json
Content-Type: application/json

{
  "toEmails": "amanda.pagani@aluno.faculdadeimpacta.com.br",
  "subject": "Teste Oh My Dog",
  "body": "<h1>Teste Oh My Dog<h1>"
}
###
