@UserAPI_HostAddress = http://localhost:5148
@UserAPI_DockerPlaygroundAddress = http://ip172-18-0-20-cn4jkpsnupig009u9jh0-5009.direct.labs.play-with-docker.com

GET {{UserAPI_HostAddress}}/api/User
Accept: application/json

###

GET {{UserAPI_HostAddress}}/api/User/1
Accept: application/json

###
GET {{UserAPI_HostAddress}}/api/User/find/12345678912
Accept: application/json

###

POST {{UserAPI_HostAddress}}/api/User/register
Accept: application/json
Content-Type: application/json

{
  "cpf": "12345678912",
  "nomeCompleto": "Clébio Machado",
  "email": "string@email.com",
  "senha": "12345678",
  "telefone": "11996853256",
  "isActive": true,
  "tipoUsuarioId": 1
}

###
POST {{UserAPI_DockerPlaygroundAddress}}/api/Usuario/cadastro
Accept: application/json
Content-Type: application/json

{
  "cpf": "12345678912",
  "nomeCompleto": "Clébio Machado",
  "email": "string@email.com",
  "senha": "12345678",
  "telefone": "11996853256",
  "isActive": true,
  "tipoUsuarioId": 1
}

###

POST {{UserAPI_HostAddress}}/api/Address/register/1
Accept: application/json
Content-Type: application/json

{
  "cep": "05792080",
  "logradouro": "Rua Mitim",
  "numero": 134,
  "bairro": "Jardim Leônidas Moreira",
  "cidade": "São Paulo",
  "uf": "SP",
  "complemento": "Bl. 02 Apto 203"
 }
###

GET {{UserAPI_HostAddress}}/api/Address/list/1
Accept: application/json

###

GET {{UserAPI_HostAddress}}/api/Address/2
Accept: application/json

###

DELETE {{UserAPI_HostAddress}}/api/Address/2
Accept: application/json

###